todolist-goof/todolist-web-struts/src/main/java/io/github/benas/todolist/web/action/AboutAction.java
/*
 * The MIT License
 *
 *   Copyright (c) 2015, Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

package io.github.benas.todolist.web.action;

import com.opensymphony.xwork2.ActionSupport;

/**
 * Action class to redirect to about page.
 *
 * @author Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 */
public class AboutAction extends ActionSupport {
    public static final String ACTIVE = "active";

    public String getAboutTabStyle() {
        return ACTIVE;
    }

}

todolist-goof/todolist-web-struts/src/main/java/io/github/benas/todolist/web/action/user/HomeAction.java
/*
 * The MIT License
 *
 *   Copyright (c) 2015, Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

package io.github.benas.todolist.web.action.user;

import com.opensymphony.xwork2.Action;
import io.github.benas.todolist.web.action.BaseAction;
import io.github.benas.todolist.web.common.util.TodoListUtils;
import io.github.todolist.core.domain.Todo;
import io.github.todolist.core.domain.User;

import java.util.List;

/**
 * Action class to load user's todo list in home page.
 * <p/>
 * benas (mahmoud.benhassine@icloud.com)
 */
public class HomeAction extends BaseAction {

    private List<Todo> todoList;

    private int totalCount;

    private int doneCount;

    private int todoCount;

    public String execute() {
        User user = getSessionUser();
        todoList = todoService.getTodoListByUser(user.getId());
        totalCount = todoList.size();
        doneCount = TodoListUtils.countTotalDone(todoList);
        todoCount = totalCount - doneCount;
        return Action.SUCCESS;
    }

    /*
     * Getters for model attributes
     */

    public List<Todo> getTodoList() {
        return todoList;
    }

    public String getHomeTabStyle() {
        return "active";
    }

    public int getTotalCount() {
        return totalCount;
    }

    public int getDoneCount() {
        return doneCount;
    }

    public int getTodoCount() {
        return todoCount;
    }

}

todolist-goof/todolist-web-struts/src/main/java/io/github/benas/todolist/web/action/user/SessionAction.java
/*
 * The MIT License
 *
 *   Copyright (c) 2015, Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 *
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:
 *
 *   The above copyright notice and this permission notice shall be included in
 *   all copies or substantial portions of the Software.
 *
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 *   THE SOFTWARE.
 */

package io.github.benas.todolist.web.action.user;

import com.opensymphony.xwork2.Action;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import io.github.benas.todolist.web.action.BaseAction;
import io.github.benas.todolist.web.common.form.LoginForm;
import io.github.benas.todolist.web.common.util.TodoListUtils;
import io.github.todolist.core.domain.User;

/**
 * Action class that controls login/logout process.
 *
 * @author Mahmoud Ben Hassine (mahmoud.benhassine@icloud.com)
 */
public class SessionAction extends BaseAction {

    private static final Logger LOGGER = LogManager.getLogger(SessionAction.class.getName());

    private LoginForm loginForm;

    private String error;

    /**
     * ******
     * Login
     * *******
     */

    public String login() {
        return Action.SUCCESS;
    }

    public String doLogin() {
        if (userService.login(loginForm.getEmail(), loginForm.getPassword())) {
            User user = userService.getUserByEmail(loginForm.getEmail());
            session.put(TodoListUtils.SESSION_USER, user);
            return Action.SUCCESS;
        } else {
            LOGGER.error("Login failed for email: " + loginForm.getEmail());
            error = getText("login.error.global.invalid");
            return Action.INPUT;
        }
    }

    /**
     * ******
     * Logout
     * *******
     */

    public String doLogout() {
        if (session instanceof org.apache.struts2.dispatcher.SessionMap) {
            try {
                ((org.apache.struts2.dispatcher.SessionMap) session).invalidate();
            } catch (IllegalStateException e) {
                LOGGER.error("Unable to invalidate session.", e);
            }
        }
        return Action.SUCCESS;
    }

    /*
     * Getters and setters for model attributes
     */

    public LoginForm getLoginForm() {
        return loginForm;
    }

    public void setLoginForm(LoginForm loginForm) {
        this.loginForm = loginForm;
    }

    public String getLoginTabStyle() {
        return "active";
    }

    public String getError() {
        return error;
    }

}

todolist-goof/todolist-web-struts/src/main/webapp/WEB-INF/views/common/header.jspf
<!DOCTYPE html>
<html lang="en">
<head>

<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href=<%= response.encodeURL(request.getContextPath() + "/static/img/todolist.ico") %>/>

<title>Todolist MVC</title>

<!-- Le styles -->
<link href=<%= response.encodeURL(request.getContextPath() + "/static/css/bootstrap.min.css") %> rel="stylesheet">
<link href=<%= response.encodeURL(request.getContextPath() + "/static/css/datepicker.css") %> rel="stylesheet">
<style type="text/css">
    body {
        padding-top: 60px;
        /* 60px to make the container go all the way to the bottom of the topbar */
    }
</style>

<!-- Le javascript -->
<script src=<%= response.encodeURL(request.getContextPath() + "/static/js/jquery-1.10.2.min.js") %> type="text/javascript"></script>
<script src=<%= response.encodeURL(request.getContextPath() + "/static/js/bootstrap.min.js") %> type="text/javascript"></script>
<script src=<%= response.encodeURL(request.getContextPath() + "/static/js/bootstrap-datepicker.js") %> type="text/javascript"></script>

</head>

<body>

<%@ include file="navigationbar.jspf"%>

todolist-goof/todolist-web-struts/src/main/webapp/WEB-INF/views/common/navigationbar.jspf
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href=<%= response.encodeURL(request.getContextPath() + "/index") %>>Todolist MVC</a>

            <%--logged in mode --%>
            <c:if test="${sessionScope.user != null}">
            <ul class="nav">
                <li class="${requestScope.homeTabStyle}"><a href=<%= response.encodeURL(request.getContextPath() + "/user/home") %>>Home</a></li>
                <li class="${requestScope.aboutTabStyle}"><a href=<%= response.encodeURL(request.getContextPath() + "/about") %>>About</a></li>
            </ul>
            <div class="btn-group pull-right">
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-user"></i> Hi ${sessionScope.user.name} ! <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href=<%= response.encodeURL(request.getContextPath() + "/user/account") %>>My account</a></li>
                    <li class="divider"></li>
                    <li><a href=<%= response.encodeURL(request.getContextPath() + "/user/logout") %>>Sign out</a></li>
                </ul>
            </div>
            </c:if>

            <%--not logged in mode --%>
            <c:if test="${sessionScope.user == null}">
            <ul class="nav pull-right">
                <li class="${requestScope.registerTabStyle}"><a href=<%= response.encodeURL(request.getContextPath() + "/register") %>>Register</a></li>
                <li class="${requestScope.loginTabStyle}"><a href=<%= response.encodeURL(request.getContextPath() + "/login") %>>Login</a></li>
            </ul>
            </c:if>

        </div>
    </div>
</div>